/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class PaymentForm extends javax.swing.JInternalFrame {
  
    /**
     * Creates new form paymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderNameTxt = new javax.swing.JTextField();
        priceLandTxt = new javax.swing.JTextField();
        areaCombobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t20RadioButton = new javax.swing.JRadioButton();
        t39RadioButton = new javax.swing.JRadioButton();
        t51RadioButton = new javax.swing.JRadioButton();
        largeLandTxt = new javax.swing.JTextField();
        availableLandTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JTextField();
        DPTxt = new javax.swing.JTextField();
        instalmentAmountTxt = new javax.swing.JTextField();
        ppnTxt = new javax.swing.JTextField();
        instalmentMonthTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        agreementCbx = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        eraseButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();
        buildingPriceTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah/m2");

        jLabel3.setText("Area");

        orderNameTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        orderNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNameTxtActionPerformed(evt);
            }
        });

        priceLandTxt.setEditable(false);
        priceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        areaCombobox.setEditable(true);
        areaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "bali", "jawa", "sumatra", " " }));
        areaCombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                areaComboboxItemStateChanged(evt);
            }
        });
        areaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboboxActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OIP.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setText("Tipe Tanah");

        jLabel6.setText("Luas Tanah Asli");

        radioButton.add(t20RadioButton);
        t20RadioButton.setText("tipe - 20");
        t20RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t20RadioButtonActionPerformed(evt);
            }
        });

        t39RadioButton.setText("tipe - 39");
        t39RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t39RadioButtonActionPerformed(evt);
            }
        });

        t51RadioButton.setText("tipe - 51");
        t51RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t51RadioButtonActionPerformed(evt);
            }
        });

        largeLandTxt.setEditable(false);
        largeLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        largeLandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeLandTxtActionPerformed(evt);
            }
        });

        availableLandTxt.setEditable(false);
        availableLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        availableLandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableLandTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Tanah Tersedia");

        jLabel8.setText("Harga");

        jLabel9.setText("DP");

        jLabel10.setText("Lama Cicilan");

        jLabel11.setText("PPN (10%)");

        jLabel12.setText("Cicilan/bln");

        totalPriceTxt.setEditable(false);
        totalPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        DPTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        instalmentAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ppnTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        instalmentMonthTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setText("Bulan");

        agreementCbx.setText("Setuju");
        agreementCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreementCbxActionPerformed(evt);
            }
        });

        saveButton.setText("SIMPAN");
        saveButton.setPreferredSize(new java.awt.Dimension(100, 23));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        eraseButton.setText("HAPUS");
        eraseButton.setPreferredSize(new java.awt.Dimension(100, 23));
        eraseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseButtonActionPerformed(evt);
            }
        });

        processButton.setText("PROSES");
        processButton.setPreferredSize(new java.awt.Dimension(100, 23));
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Harga bangunan termasuk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(t51RadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(t20RadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t39RadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(largeLandTxt)
                        .addComponent(availableLandTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(buildingPriceTxt))
                    .addComponent(jLabel14))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(processButton, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eraseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(instalmentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(instalmentMonthTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(ppnTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agreementCbx)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(priceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t20RadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t39RadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(largeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(availableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPriceTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(instalmentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addComponent(t51RadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agreementCbx))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instalmentMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eraseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderNameTxtActionPerformed

    private void areaComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_areaComboboxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_areaComboboxItemStateChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(agreementCbx.isSelected()== false){
            JOptionPane.showMessageDialog(null, 
                    "Klik simpan untuk menyimpan data", "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }else {
            String typeHouse;
            if(t20RadioButton.isSelected()){
                typeHouse ="TIPE 20";
            }else if(t39RadioButton.isSelected()){
                typeHouse = "TIPE 39";
            }else{
                typeHouse = "TIPE 51";
            }
            
            try {
                String sql = "INSERT INTO RUMAH (name, area, tipe, luas, harga, jumlah_cicilan, cicilan_bulan) VALUES ('"
                        + orderNameTxt.getText() + "','"
                        + areaCombobox.getSelectedItem() + "','"
                        + typeHouse + "','"
                        + largeLandTxt.getText() + "','"
                        + totalPriceTxt.getText() + "','"
                        + instalmentAmountTxt.getText() + "','"
                        + instalmentMonthTxt.getText() + "')";
            Connection conn = (Connection)ConnectionDb.connectDatabase();
            PreparedStatement pst = (PreparedStatement)conn.prepareStatement(sql);
            pst.execute();
            }catch (SQLException ex){
                Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            OptionMenu optionMenu = new OptionMenu();
            optionMenu.setVisible(true);
            this.getDesktopPane().add(optionMenu);
            this.dispose();
        }

    }//GEN-LAST:event_saveButtonActionPerformed

  
    private void eraseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseButtonActionPerformed
        orderNameTxt.setText("");
        priceLandTxt.setText("");
        largeLandTxt.setText("");
        availableLandTxt.setText("");
        DPTxt.setText("");
        instalmentAmountTxt.setText("");
        instalmentMonthTxt.setText("");
        ppnTxt.setText("");
        areaCombobox.setSelectedIndex(0);
        radioButton.clearSelection();
        totalPriceTxt.setText("");
        agreementCbx.setSelected(false);
    }//GEN-LAST:event_eraseButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        if(totalPriceTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "pilihan belum lengkap");
        }else if (DPTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DP harus diiisi");
        }else if (instalmentAmountTxt.getText(). isEmpty()){
            JOptionPane.showMessageDialog(null, "isi jumlah cicilan yang diinginkan");
        }else {
            long landPrice = Long.parseLong(priceLandTxt.getText()),
                     buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                     availableLand = Long.parseLong(availableLandTxt.getText()),
                     dp = Long.parseLong(DPTxt.getText()),
                     instalmentAmount = Long.parseLong(instalmentAmountTxt.getText()),
                     totalPrice, ppn, instalmentPerMonth;
            totalPrice = (availableLand * landPrice) + buildingPrice;
            ppn = totalPrice * 10 / 100;
            instalmentPerMonth = (totalPrice + ppn)/ instalmentAmount;
            ppnTxt.setText("" + ppn);
            instalmentMonthTxt.setText("" + instalmentPerMonth);
        }
    }//GEN-LAST:event_processButtonActionPerformed

    private void areaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboboxActionPerformed
        switch(areaCombobox.getSelectedIndex()){
            case 0:
                priceLandTxt.setText("");
                buildingPriceTxt.setText("");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                DPTxt.setText("");
                instalmentAmountTxt.setText("");
                instalmentMonthTxt.setText("");
                ppnTxt.setText("");
                areaCombobox.setSelectedIndex(0);
                radioButton.clearSelection();
                totalPriceTxt.setText("");
                agreementCbx.setSelected(false);
                break;
                
            case 1:
                priceLandTxt.setText("12000000");
                buildingPriceTxt.setText("2330000");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                DPTxt.setText("");
                instalmentAmountTxt.setText("");
                instalmentMonthTxt.setText("");
                ppnTxt.setText("");
                
                radioButton.clearSelection();
                totalPriceTxt.setText("");
                agreementCbx.setSelected(false);
                break; 
                
            case 2:
                priceLandTxt.setText("30000000");
                buildingPriceTxt.setText("990000");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                DPTxt.setText("");
                instalmentAmountTxt.setText("");
                instalmentMonthTxt.setText("");
                ppnTxt.setText("");
               
                radioButton.clearSelection();
                totalPriceTxt.setText("");
                agreementCbx.setSelected(false);
                break;
                
            case 3:
                priceLandTxt.setText("44000000");
                buildingPriceTxt.setText("1230000");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                DPTxt.setText("");
                instalmentAmountTxt.setText("");
                instalmentMonthTxt.setText("");
                ppnTxt.setText("");
               
                radioButton.clearSelection();
                totalPriceTxt.setText("");
                agreementCbx.setSelected(false);
                break;
                
                
        }
    }//GEN-LAST:event_areaComboboxActionPerformed

    private void t20RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t20RadioButtonActionPerformed
         if (areaCombobox.getSelectedIndex() == 0){
             JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
             radioButton.clearSelection();
         }else {
             largeLandTxt.setText("4000000");
             availableLandTxt.setText("20");
             long landPrice = Long.parseLong(priceLandTxt.getText()),
                     buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                     availableLand = Long.parseLong(availableLandTxt.getText()),
                     totalPrice;
             totalPrice = (availableLand * landPrice) + buildingPrice;
             totalPriceTxt.setText("" + totalPrice);
             
             instalmentAmountTxt.setText("");
             DPTxt.setText("");
             ppnTxt.setText("");
             instalmentMonthTxt.setText("");
                     
         }
    }//GEN-LAST:event_t20RadioButtonActionPerformed

    private void t39RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t39RadioButtonActionPerformed
         if (areaCombobox.getSelectedIndex() == 0){
             JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
             radioButton.clearSelection();
         }else {
             largeLandTxt.setText("2000000");
             availableLandTxt.setText("39");
             long landPrice = Long.parseLong(priceLandTxt.getText()),
                     buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                     availableLand = Long.parseLong(availableLandTxt.getText()),
                     totalPrice;
             totalPrice = (availableLand * landPrice) + buildingPrice;
             totalPriceTxt.setText("" + totalPrice);
             
             instalmentAmountTxt.setText("");
             DPTxt.setText("");
             ppnTxt.setText("");
             instalmentMonthTxt.setText("");
                     
                     
         }
        
        
    }//GEN-LAST:event_t39RadioButtonActionPerformed

    private void t51RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t51RadioButtonActionPerformed
        if (areaCombobox.getSelectedIndex() == 0){
             JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
             radioButton.clearSelection();
         }else {
             largeLandTxt.setText("9900000");
             availableLandTxt.setText("51");
             long landPrice = Long.parseLong(priceLandTxt.getText()),
                     buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                     availableLand = Long.parseLong(availableLandTxt.getText()),
                     totalPrice;
             totalPrice = (availableLand * landPrice) + buildingPrice;
             totalPriceTxt.setText("" + totalPrice);
                    
             instalmentAmountTxt.setText("");
             DPTxt.setText("");
             ppnTxt.setText("");
             instalmentMonthTxt.setText("");
                     
         }
      
       
    }//GEN-LAST:event_t51RadioButtonActionPerformed

    private void availableLandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableLandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableLandTxtActionPerformed

    private void largeLandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeLandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeLandTxtActionPerformed

    private void agreementCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreementCbxActionPerformed
        if(orderNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama pemesan harus diisi");
            agreementCbx.setSelected(false);
        }else if (ppnTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "tekan tombol proses terlebih dahulu");
            agreementCbx.setSelected(false);
        }else if (agreementCbx.isSelected() == true){
            JOptionPane.showMessageDialog(null, "pemesan menyetujui");
            agreementCbx.setSelected(true);
        }else {
        JOptionPane.showMessageDialog(null, "pesanan belum disetujui");
        agreementCbx.setSelected(false);
        }
    }//GEN-LAST:event_agreementCbxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPTxt;
    private javax.swing.JCheckBox agreementCbx;
    private javax.swing.JComboBox<String> areaCombobox;
    private javax.swing.JTextField availableLandTxt;
    private javax.swing.JTextField buildingPriceTxt;
    private javax.swing.JButton eraseButton;
    private javax.swing.JTextField instalmentAmountTxt;
    private javax.swing.JTextField instalmentMonthTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField largeLandTxt;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField ppnTxt;
    private javax.swing.JTextField priceLandTxt;
    private javax.swing.JButton processButton;
    private javax.swing.ButtonGroup radioButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton t20RadioButton;
    private javax.swing.JRadioButton t39RadioButton;
    private javax.swing.JRadioButton t51RadioButton;
    private javax.swing.JTextField totalPriceTxt;
    // End of variables declaration//GEN-END:variables
}
